Stranzhay/animation support
metaplex-foundation/sugar pull request #212
Opened 2022-05-15 02:20 UTC by stranzhay

2022-05-22 00:29 UTC, febo requested changes
It is working fine, just minor comments.

2022-05-22 00:29 UTC, febo commented on src/upload/assets.rs
> +    if let Some(animation) = animation_link.clone() {
The `properties.files` is not enforced and it may go away in the future.  Perhaps we can do the same approach as the image (for loop above).

2022-05-22 00:29 UTC, febo commented on src/utils.rs
> +    // forces the progress bar to show imimagetely
Not sure about this change. 😀

2022-05-22 00:29 UTC, febo commented on src/upload/process.rs
> +    println!("| images     | {:>6} |", indices.image.len());
Remove 1 space between `"images"` and `"|"` to fix the alignment.

2022-05-22 00:29 UTC, febo commented on src/upload/process.rs
> +    println!("| metadata   | {:>6} |", indices.metadata.len());
Remove 1 space between `"metadata"` and `"|"` to fix the alignment.

2022-05-22 00:29 UTC, febo commented on src/upload/process.rs
> +        println!("| animation  | {:>6} |", indices.animation.len());
Remove 1 space between `"animation"` and `"|"` to fix the alignment.

2022-05-23 01:30 UTC, stranzhay commented on src/utils.rs
> +    // forces the progress bar to show imimagetely
haha unintentional

2022-05-23 10:10 UTC, febo commented on README.md
> +- better performance for upload of image/metadata files and deploy of the candy machine &mdash; these operations take advantage of multithreaded systems to significantly speed up the computational ti
Wonder if we should keep `media` since it represent both images and videos (animation).

2022-05-23 10:11 UTC, febo commented on README.md
> +Create a folder named `assets` to store your json and image file pairs with the naming convention 0.json, 0.<ext>, 1.json, 1.<ext>, etc., where the extension is `.png`, `.jpg`, etc. This is the same
Same as the previous comment.

2022-05-23 18:00 UTC, stegaBOB requested changes
Img => Image, Movie => Animation

2022-05-23 18:57 UTC, stranzhay commented on src/upload/assets.rs
> +    Movie,
I went with Img and Movie is because thats how they appear on the docs site as asset types.

2022-05-23 20:52 UTC, febo commented on src/upload/assets.rs
> +    }
We can simplify a bit the logic here, removing some `clone`'s and `unwrap`'s:

```
for file in &mut metadata.properties.files {
    if file.uri.eq(&metadata.image) {
        file.uri = image_link.to_string();
    }
    if let Some(ref animation_link) = animation_link {
        if let Some(ref animation_url) = metadata.animation_url {
            if file.uri.eq(animation_url) {
                file.uri = animation_link.to_string();
            }
        }
    }
}

metadata.image = image_link.to_string();
metadata.animation_url = animation_link;
```

2022-05-24 00:19 UTC, febo approved these changes

2022-05-24 00:54 UTC, merged